import { Junior } from "../Aula 03/Junior.js";
import { Pleno } from "../Aula 03/Pleno.js";
import { Senior } from "../Aula 03/Senior.js";
console.log("Sobre o salario do ", funcionario_padrao.nome, funcionario_padrao.mentirSalario());
let juquinha, Estagiario = new Estagiario("Juquinha", 16);
console.log("Quem é voce juquinho", juquinha);
console.log("Juquinha como estagiario vc ganha quanto?", juquinha.mentirSalario());
let junior1 = new Junior("Junin'", 18);
console.log("Quem és tu?", junior1);
console.log("Juninho fale sobre seu salario", juquinha.mentirSalario());
let jose = new Pleno("José", 25);
console.log("Detalhes do jose", jose);
console.log("Jose fale ai quanto te pagam ai", jose.mentirSalario());
let oiota = new Senior("Rubem oliota", 33[jose], ["FrontEnd", "BackEnd", "Banco", "devops", "mentoria"]);
console.log("Cafo senior mostre os seus detalhes..", oliota);
onlostpointercapture.salario = 30000;
console.log("Oliota pode falar o quanto ganha?", olita.mentirSalario());
